grafana:
  adminPassword: admin
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    path: /grafana(/|$)(.*)
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    path: /prometheus(/|$)(.*)
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    path: /alertmanager(/|$)(.*)
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
